/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface StablePostInterface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOMINATOR" | "MAX_FEE_BPS" | "creatorBalances" | "owner" | "platformFee" | "platformFeesCollected" | "postEarnings" | "renounceOwnership" | "setPlatformFee" | "tipCreator" | "totalTips" | "totalVolume" | "transferOwnership" | "usdc" | "withdraw" | "withdrawPlatformFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "PlatformFeeUpdated" | "PlatformFeesWithdrawn" | "Tipped" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'creatorBalances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'platformFeesCollected', values?: undefined): string;
encodeFunctionData(functionFragment: 'postEarnings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPlatformFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'tipCreator', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalTips', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVolume', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawPlatformFees', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creatorBalances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'platformFeesCollected', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'postEarnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPlatformFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tipCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTips', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVolume', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawPlatformFees', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PlatformFeesWithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TippedEvent {
      export type InputTuple = [sender: AddressLike, creator: AddressLike, postId: BigNumberish, amount: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [sender: string, creator: string, postId: bigint, amount: bigint, fee: bigint];
      export interface OutputObject {sender: string, creator: string, postId: bigint, amount: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [creator: string, amount: bigint];
      export interface OutputObject {creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface StablePost extends BaseContract {
    
    connect(runner?: ContractRunner | null): StablePost;
    waitForDeployment(): Promise<this>;

    interface: StablePostInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    creatorBalances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    platformFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    platformFeesCollected: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    postEarnings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPlatformFee: TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    tipCreator: TypedContractMethod<
      [creator: AddressLike, postId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    totalTips: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalVolume: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawPlatformFees: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'creatorBalances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'platformFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'platformFeesCollected'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'postEarnings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPlatformFee'): TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tipCreator'): TypedContractMethod<
      [creator: AddressLike, postId: BigNumberish, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalTips'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalVolume'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawPlatformFees'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PlatformFeeUpdated'): TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
getEvent(key: 'PlatformFeesWithdrawn'): TypedContractEvent<PlatformFeesWithdrawnEvent.InputTuple, PlatformFeesWithdrawnEvent.OutputTuple, PlatformFeesWithdrawnEvent.OutputObject>;
getEvent(key: 'Tipped'): TypedContractEvent<TippedEvent.InputTuple, TippedEvent.OutputTuple, TippedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PlatformFeeUpdated(uint256,uint256)': TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
      PlatformFeeUpdated: TypedContractEvent<PlatformFeeUpdatedEvent.InputTuple, PlatformFeeUpdatedEvent.OutputTuple, PlatformFeeUpdatedEvent.OutputObject>;
    

      'PlatformFeesWithdrawn(address,uint256)': TypedContractEvent<PlatformFeesWithdrawnEvent.InputTuple, PlatformFeesWithdrawnEvent.OutputTuple, PlatformFeesWithdrawnEvent.OutputObject>;
      PlatformFeesWithdrawn: TypedContractEvent<PlatformFeesWithdrawnEvent.InputTuple, PlatformFeesWithdrawnEvent.OutputTuple, PlatformFeesWithdrawnEvent.OutputObject>;
    

      'Tipped(address,address,uint256,uint256,uint256)': TypedContractEvent<TippedEvent.InputTuple, TippedEvent.OutputTuple, TippedEvent.OutputObject>;
      Tipped: TypedContractEvent<TippedEvent.InputTuple, TippedEvent.OutputTuple, TippedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }